language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  sonarqube:
      token:
        secure: ${SONAR_TOKEN}
      branches:
        - master
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g grunt-cli
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install
  - bower install
  - npm update
  - bower update

script:
  - gulp clean verify build
  - xvfb-run wct --skip-plugin local
 # - if [“${TRAVIS_PULL_REQUEST}” = “false” ]; then wct -s ‘default’; fi

after_success:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'

