language: node_js
node_js:
- "8"
dist: trusty
sudo: false

addons:
  chrome: stable
  firefox: latest
  sauce_connect: false

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm run install:all

script:
- npm run lint
- npm run test:firefox
