language: node_js
node_js: stable
dist: trusty
sudo: required

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  firefox: latest
  sauce_connect: false

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install --global bower
- npm install
- bower install --force-latest
- npm update
- bower update --force-latest

script:
- npm run-script build
- npm run-script lint
- npm run-script test