language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  sonarqube:
      token:
        secure: 81d352154f4bc4b710ed661bb04d67fabc19b0e6
  branches:
      - master
      - CreateSonarReportsForDolphinPolymer
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install
  - bower install
  - npm update
  - bower update

script:
  - gulp clean verify build
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

