language: node_js
node_js: stable
dist: trusty
sudo: required

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  firefox: latest
  sauce_connect: false

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install -g bower
- npm install
- bower install
- npm update
- bower update

script:
- wct --skip-plugin sauce